packages:
  - 'apps/*'
  - 'packages/*'
  - 'contracts'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  '@nestjs/core': true
  keccak: true
  secp256k1: true
  bufferutil: true
  utf-8-validate: true
  '@parcel/watcher': true

# pnpm 10 (dipakai Vercel) memakai onlyBuiltDependencies
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - esbuild
  - keccak
  - secp256k1
