/** Registry error code — lihat API SPEC DETAIL §9. */
export const ERROR_CODES = {
  AUTH_UNAUTHENTICATED: 401,
  AUTH_FORBIDDEN: 403,
  CAMPAIGN_NOT_FOUND: 404,
  CAMPAIGN_NOT_ACTIVE: 409,
  CAMPAIGN_NOT_OWNED: 403,
  CAMPAIGN_INVALID_STATUS: 409,
  CAMPAIGN_FROZEN: 409,
  CAMPAIGN_PROPOSAL_MISSING: 400,
  CAMPAIGN_DEADLINE_PASSED: 400,
  CAMPAIGN_DEADLINE_TOO_SOON: 400,
  DONATION_NOT_FOUND: 404,
  DONATION_AMOUNT_INVALID: 400,
  DONATION_DUPLICATE: 409,
  DONATION_ALREADY_PAID: 409,
  IDEMPOTENCY_KEY_REQUIRED: 400,
  PAYMENT_SIGNATURE_INVALID: 401,
  PAYMENT_AMOUNT_MISMATCH: 400,
  PAYMENT_NOT_FOUND: 404,
  PAYMENT_PROVIDER_ERROR: 502,
  INVALID_FILE_TYPE: 400,
  FILE_TOO_LARGE: 400,
  BLOCKCHAIN_NOT_NOTARIZED: 400,
  BLOCKCHAIN_RPC_ERROR: 503,
  BLOCKCHAIN_INVALID_STATUS: 409,
  DISBURSEMENT_NOT_ELIGIBLE: 409,
  DISBURSEMENT_PROOF_REQUIRED: 400,
  DISBURSEMENT_AMOUNT_EXCEEDS: 400,
  DISBURSEMENT_INVALID_STATUS: 409,
  DISBURSEMENT_NOT_FOUND: 404,
  VALIDATION_ERROR: 400,
  NOT_FOUND: 404,
  DEV_TOOLS_DISABLED: 404,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

export interface ApiSuccess<T> {
  success: true;
  data: T;
}

export interface ApiFailure {
  success: false;
  error: { code: ErrorCode; message: string; details?: unknown };
}

export type ApiResponse<T> = ApiSuccess<T> | ApiFailure;
